version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}

#  users_pgadmin:
#    container_name: users_pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
#      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres

  fastapi_server:
    container_name: fastapi_server
    build: .
    command: bash -c "alembic upgrade head && python3.12 main.py"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure