"""Init

Revision ID: 2fb10a3965ed
Revises: 
Create Date: 2024-09-07 13:06:23.489960

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from fastapi_users_db_sqlalchemy import GUID

# revision identifiers, used by Alembic.
revision: str = '2fb10a3965ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False, comment='Электронная почта'),
    sa.Column('username', sa.String(length=32), nullable=False, comment='Имя пользователя'),
    sa.Column('first_name', sa.String(length=32), nullable=False, comment='Имя'),
    sa.Column('last_name', sa.String(length=32), nullable=False, comment='Фамилия'),
    sa.Column('patronymic', sa.String(length=32), nullable=True, comment='Отчество'),
    sa.Column('position', sa.String(length=256), nullable=False, comment='Должность'),
    sa.Column('task_type', sa.String(length=32), nullable=False, comment='Тип задачи'),
    sa.Column('device_verification_code', sa.String(length=10), nullable=True, comment='Код подтверждения для устройства'),
    sa.Column('registered_at', sa.DateTime(), nullable=False, comment='Дата регистрации'),
    sa.Column('hashed_password', sa.String(length=256), nullable=False, comment='Хэшированный пароль'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен?'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Суперпользователь?'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Верифицирован?'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
