"""new fields

Revision ID: 7ae3191d9281
Revises: be47e8942289
Create Date: 2024-09-08 12:43:06.902152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae3191d9281'
down_revision: Union[str, None] = 'be47e8942289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('task_done', sa.Boolean(), nullable=True, comment='Статус задачи'))
    op.add_column('user', sa.Column('expected_result', sa.JSON(), nullable=True, comment='Ожидаемый результат'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'expected_result')
    op.drop_column('user', 'task_done')
    # ### end Alembic commands ###
